name: Documentation CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "ci-documentation-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:
  build-documentation:
    name: Build Documentation
    runs-on: macos-14
    env:
      SWIFTCI_DOCC: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift package generate-documentation --product PoliceDataKit
