name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "**/*.swift"
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:
  build-test:
    name: Build and Test
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build -Xswiftc -warnings-as-errors --build-tests

      - name: Test
        run: swift test --skip-build --parallel --filter PoliceDataKitTests
      
      - name: Build for Release
        run: swift build -c release -Xswiftc -warnings-as-errors
  
  build-and-test-platforms:
    name: Build and Test (${{ matrix.name }})
    runs-on: macos-14
    continue-on-error: true
    strategy:
      matrix:
        include:
          - name: iOS
            destination: platform=iOS Simulator,name=iPhone 15,OS=17.2
          - name: watchOS
            destination: platform=watchOS Simulator,name=Apple Watch Series 9 (45mm),OS=10.2
          - name: tvOS
            destination: platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=17.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: set -o pipefail && env NSUnbufferedIO=YES && xcodebuild build-for-testing -scheme PoliceDataKit -only-testing PoliceDataKitTests -destination '${{ matrix.destination }}' | xcpretty
      
      - name: Test
        run: set -o pipefail && env NSUnbufferedIO=YES && xcodebuild test-without-building -scheme PoliceDataKit -only-testing PoliceDataKitTests -destination '${{ matrix.destination }}' | xcpretty
