name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  lint:
    name: Lint
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Lint
        run: swift package plugin swiftlint --strict --reporter github-actions-logging

  build-test-macos:
    name: Build and Test (macOS)
    runs-on: macos-13
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift build --build-tests

      - name: Test
        run: swift test --skip-build --parallel

  build-test-ios:
    name: Build and Test (iOS)
    runs-on: macos-13
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          set -o pipefail && \
          xcodebuild build-for-testing \
          -scheme PoliceDataKit \
          -destination "platform=iOS Simulator;name=iPhone 14 Pro Max" \
          | xcpretty

      - name: Test
        run: |
          set -o pipefail && \
          xcodebuild test-without-building \
          -scheme PoliceDataKit \
          -destination "platform=iOS Simulator;name=iPhone 14 Pro Max" \
          | xcpretty

  codeScan:
    name: Code Scan
    runs-on: ubuntu-latest
    permissions:
        security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Scan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

  build-documentation:
    name: Build Documentation
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache SPM
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift package generate-documentation --product PoliceDataKit
